name: GPT Code Critic
description: "Run GPT Code Critic to analyze code changes!"
inputs:
  openai_api_key:
    description: "API key for OpenAI GPT"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run GPT Code Critic
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
      run: python3 main.py

    - name: Check if results.sarif exists
      shell: bash
      run: |
        if [ ! -f results.sarif ]; then
          echo "::error::results.sarif not found"
          exit 1
        fi

    - name: Print results
      shell: bash
      run: |
        cat results.sarif

    - name: Upload results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
      env:
        GITHUB_TOKEN: ${{ github.token }}
