name: GPT Code Critic
description: "Run GPT Code Critic to analyze code changes!"
branding:
  icon: 'aperture'
  color: 'gray-dark'
inputs:
  openai_api_key:
    description: "API key for OpenAI GPT"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py

    # - name: Run GPT Code Critic
    #   shell: bash
    #   env:
    #     OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    #   run: |
    #     docker run --rm -v ${{ github.workspace }}:${{ github.workspace }} -e OPENAI_API_KEY=$OPENAI_API_KEY openai/gpt-code-critic:latest python3 /${{ github.action_path }}/main.py

    - name: Check if results.sarif exists
      shell: bash
      run: |
        if [ ! -f ${{ github.action_path }}/results.sarif ]; then
          echo "::error::results.sarif not found"
          exit 1
        fi

    - name: Print results
      shell: bash
      run: |
        cat ${{ github.action_path }}/results.sarif

    - name: Upload results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ github.action_path }}/results.sarif
      env:
        GITHUB_TOKEN: ${{ github.token }}
