name: GPT Code Critic

on:
  push:
    branches: [main]

jobs:
  analyze-code:
    name: Test action
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GPT Code Critic
        uses: actions/gpt-code-critic-action@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
